version: '3.8'
services:
  php:
    build: ./api/docker/php
    container_name: travel_app_php_c
    ports: 
      - 9000:9000
    volumes:
      - ./api/symfony/:/var/www/symfony:cached
  nginx:
    build: ./api/docker/nginx
    container_name: travel_app_nginx_c
    ports:
      - 8080:80
    volumes:
      - ./api/symfony/:/var/www/symfony:cached
  client:
    build: ./client
    container_name: travel_app_react_c
    ports:
      - 3000:3000
    volumes:
      - ./client/:/client
      - /client/node_modules